<?php

return [

    /*
    |--------------------------------------------------------------------------
    | API Prefix
    |--------------------------------------------------------------------------
    |
    | This value is the prefix of all API routes. The prefix is applied to
    | all routes generated by the package. You can customize it to match
    | your application's needs.
    |
    */

    'prefix' => env('API_PREFIX', 'api'),

    /*
    |--------------------------------------------------------------------------
    | API Version
    |--------------------------------------------------------------------------
    |
    | This value is the default version of your API. It will be used in the
    | route prefix and in the response headers.
    |
    */

    'version' => env('API_VERSION', 'v1'),

    /*
    |--------------------------------------------------------------------------
    | API Rate Limiting
    |--------------------------------------------------------------------------
    |
    | This value controls the rate limiting for your API endpoints. You can
    | set the maximum number of requests per minute.
    |
    */

    'rate_limit' => [
        'enabled' => env('API_RATE_LIMIT_ENABLED', true),
        'max_attempts' => env('API_RATE_LIMIT_MAX_ATTEMPTS', 60),
        'decay_minutes' => env('API_RATE_LIMIT_DECAY_MINUTES', 1),
    ],

    /*
    |--------------------------------------------------------------------------
    | API Authentication
    |--------------------------------------------------------------------------
    |
    | This value controls the authentication method for your API. Currently
    | supported methods are: sanctum, token
    |
    */

    'auth' => [
        'driver' => env('API_AUTH_DRIVER', 'sanctum'),
        'guard' => env('API_AUTH_GUARD', 'sanctum'),
        'token_field' => 'api_token',
    ],

    /*
    |--------------------------------------------------------------------------
    | API Response Format
    |--------------------------------------------------------------------------
    |
    | This value controls the default response format for your API. You can
    | customize the structure of success and error responses.
    |
    */

    'response' => [
        'success_key' => env('API_SUCCESS_KEY', 'data'),
        'message_key' => env('API_MESSAGE_KEY', 'message'),
        'error_key' => env('API_ERROR_KEY', 'error'),
        'meta_key' => env('API_META_KEY', 'meta'),
        'links_key' => env('API_LINKS_KEY', 'links'),
        'include_pagination_links' => env('API_PAGINATION_LINKS', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | API Transformers
    |--------------------------------------------------------------------------
    |
    | This value controls the default transformer settings. Transformers are
    | used to convert your models to API responses.
    |
    */

    'transformers' => [
        'default_includes' => [],
        'auto_transform' => env('API_AUTO_TRANSFORM', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | API Caching
    |--------------------------------------------------------------------------
    |
    | This value controls the caching for your API responses. You can enable
    | or disable caching and set the default cache TTL.
    |
    */

    'cache' => [
        'enabled' => env('API_CACHE_ENABLED', false),
        'ttl' => env('API_CACHE_TTL', 30), // in minutes
    ],

    /*
    |--------------------------------------------------------------------------
    | API Exceptions
    |--------------------------------------------------------------------------
    |
    | This value controls how exceptions are handled in your API. You can
    | choose to show detailed error messages in development.
    |
    */

    'exceptions' => [
        'debug' => env('API_EXCEPTION_DEBUG', false),
        'hide_exception_message' => env('API_HIDE_EXCEPTION_MESSAGE', true),
        'default_exception_message' => env('API_DEFAULT_EXCEPTION_MESSAGE', 'An error occurred. Please try again later.'),
    ],

    /*
    |--------------------------------------------------------------------------
    | API Validation
    |--------------------------------------------------------------------------
    |
    | This value controls the default validation settings for your API.
    |
    */

    'validation' => [
        'error_format' => 'laravel', // laravel, flat
        'include_field_in_error' => env('API_VALIDATION_INCLUDE_FIELD', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | API CORS
    |--------------------------------------------------------------------------
    |
    | This value controls the Cross-Origin Resource Sharing settings for your API.
    |
    */

    'cors' => [
        'enabled' => env('API_CORS_ENABLED', true),
        'allowed_origins' => env('API_CORS_ALLOWED_ORIGINS', '*'),
        'allowed_methods' => env('API_CORS_ALLOWED_METHODS', 'GET, POST, PUT, PATCH, DELETE, OPTIONS'),
        'allowed_headers' => env('API_CORS_ALLOWED_HEADERS', 'Content-Type, Authorization, X-Requested-With, Accept, Origin'),
        'allow_credentials' => env('API_CORS_ALLOW_CREDENTIALS', 'false'),
    ],

];